-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Φιλοξενητής: localhost:3306
-- Χρόνος δημιουργίας: 27 Οκτ 2020 στις 23:26:03
-- Έκδοση διακομιστή: 5.7.32
-- Έκδοση PHP: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Βάση δεδομένων: `marketin_kiroupan658550_wordpress_d`
--

-- --------------------------------------------------------

--
-- Δομή πίνακα για τον πίνακα `8RyLi_posts`
--

CREATE TABLE `8RyLi_posts` (
  `ID` bigint(20) UNSIGNED NOT NULL,
  `post_author` bigint(20) UNSIGNED NOT NULL DEFAULT '0',
  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `post_password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `post_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `to_ping` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `pinged` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_parent` bigint(20) UNSIGNED NOT NULL DEFAULT '0',
  `guid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `menu_order` int(11) NOT NULL DEFAULT '0',
  `post_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'post',
  `post_mime_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_count` bigint(20) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Άδειασμα δεδομένων του πίνακα `8RyLi_posts`
--

INSERT INTO `8RyLi_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(512, 1, '2018-05-15 17:27:19', '2018-05-15 17:27:19', 'ЛАГИРОС\r\n\r\nЗащитная географическая зона.\r\n\r\nКрасное сухое биологическое вино Икарии.\r\n\r\nНевероятное Фокиано и буйный характер Кофдуро\r\n\r\n(Mandilaria) объединяют свои достоинства в вине с рубиновым цветом, с ароматом диких цветов и черных фруктов.\r\n\r\nРекомендуется пить вино,охлажденным до 15 - 17˚C.\r\n\r\nИдельно сочетается с блюдами Средиземной кухни.', 'Lagyros -BIO', 'ЛАГИРОС\r\n\r\nЗащитная географическая зона.\r\n\r\nКрасное сухое биологическое вино Икарии.\r\n\r\nНевероятное Фокиано и буйный характер Кофдуро\r\n\r\n(Mandilaria) объединяют свои достоинства в вине с рубиновым цветом, с ароматом диких цветов и черных фруктов.\r\n\r\nРекомендуется пить вино,охлажденным до 15 - 17˚C.\r\n\r\nИдельно сочетается с блюдами Средиземной кухни.', 'publish', 'closed', 'closed', '', 'lagyros', '', '', '2018-05-15 17:29:20', '2018-05-15 17:29:20', '', 0, 'http://luculos.com/?product=lagyros-2', 0, 'al_product', '', 0),
(839, 1, '2020-07-17 17:55:18', '2020-07-17 17:55:18', '<img class=\"alignnone wp-image-846\" src=\"https://luculos.com/wp-content/uploads/2020/07/20200119_150343-2.jpg\" alt=\"Dellagrazia Extra Virgin Olive Oil\" width=\"337\" height=\"253\" /> <img class=\"alignnone wp-image-847\" src=\"https://luculos.com/wp-content/uploads/2020/07/20200119_153320-2.jpg\" alt=\"Dellagrazia Extra Virgin Olive Oil\" width=\"339\" height=\"254\" />\r\n<p class=\"western\" lang=\"el-GR\"><span style=\"color: #222222;\"><span style=\"font-family: Arial, sans-serif;\"><span style=\"font-size: medium;\"><span lang=\"en-US\">Dellagrazia Extra Virgin Olive Oil is a cold-pressed product. Our olive trees are grown on the sunny island of Syros. </span></span></span></span><span style=\"color: #222222;\"><span style=\"font-family: Arial, sans-serif;\"><span style=\"font-size: medium;\">Ο</span></span></span><span style=\"color: #222222;\"><span style=\"font-family: Arial, sans-serif;\"><span style=\"font-size: medium;\"><span lang=\"en-US\">live grove is located in the SW of the island in a coastal location. </span></span></span></span><span style=\"color: #222222;\"><span style=\"font-family: Arial, sans-serif;\"><span style=\"font-size: medium;\">Τ</span></span></span><span style=\"color: #222222;\"><span style=\"font-family: Arial, sans-serif;\"><span style=\"font-size: medium;\"><span lang=\"en-US\">he fruit absorbs all the beneficial properties of the sea air.\r\nDellagrazia Extra Virgin Olive Oil contains characteristics that determine the quality of olive oil such as rich fruity aroma and a refreshing taste as well as a powerful antioxidant effect.\r\nDellagrazia Extra Virgin Olive Oil has a golden-green hue, a balanced spicy taste with a sweet, light aftertaste that lasts. Its wonderful fruity aroma, with touches of pear and almond, is due to the olive tree variety \"Koroneiki\" from which it is produced.\r\nThe integrated cultivation and harvesting methods in combination with modern production and storage methods ensure its special characteristics and superior quality.</span></span></span></span></p>', 'Dellagrazia Extra Virgin Olive Oil', '', 'publish', 'closed', 'closed', '', 'dellagrazia-extra-virgin-olive-oil', '', '', '2020-07-17 18:54:13', '2020-07-17 18:54:13', '', 0, 'https://luculos.com/?post_type=al_product&#038;p=839', 0, 'al_product', '', 0),
(840, 1, '2020-07-17 18:01:01', '2020-07-17 18:01:01', '<img class=\"alignnone wp-image-846\" src=\"https://luculos.com/wp-content/uploads/2020/07/20200119_150343-2.jpg\" alt=\"Natives Olivenöl Extra von Dellagrazia\" width=\"337\" height=\"253\" /> <img class=\"alignnone wp-image-847\" src=\"https://luculos.com/wp-content/uploads/2020/07/20200119_153320-2.jpg\" alt=\"Natives Olivenöl Extra von Dellagrazia\" width=\"339\" height=\"254\" />\r\n<p class=\"western\">Natives Olivenöl Extra von Dellagrazia ist ein kaltgepresstes Produkt. Unsere Olivenbäume wachsen auf der sonnigen Insel Syros. Die Olivenplantage befindet sich im Südwesten der Insel an einer Küstenlage. Die Frucht nimmt alle vorteilhaften Eigenschaften der Seeluft auf.\r\nNatives Olivenöl Extra von Dellagrazia enthält Eigenschaften, die die Qualität von Olivenöl bestimmen, wie ein reiches fruchtiges Aroma und einen erfrischenden Geschmack sowie eine starke antioxidative Wirkung.\r\nNatives Olivenöl Extra von Dellagrazia hat einen goldgrünen Farbton, einen ausgewogenen, würzigen Geschmack mit einem süßen, leichten Nachgeschmack, der anhält. Sein wunderbar fruchtiges Aroma mit einem Hauch von Birne und Mandel ist auf die Olivenbaumsorte \"Koroneiki\" zurückzuführen, aus der es hergestellt wird.\r\nDie integrierten Anbau- und Erntemethoden in Kombination mit modernen Produktions- und Lagermethoden gewährleisten die besonderen Eigenschaften und die überlegene Qualität.</p>', 'Natives Olivenöl Extra von Dellagrazia', '', 'publish', 'closed', 'closed', '', 'natives-olivenol-extra-von-dellagrazia', '', '', '2020-07-18 09:51:46', '2020-07-18 09:51:46', '', 0, 'https://luculos.com/?post_type=al_product&#038;p=840', 0, 'al_product', '', 0),
(853, 1, '2020-07-17 18:42:24', '2020-07-17 18:42:24', '<img class=\"alignnone wp-image-846\" src=\"https://luculos.com/wp-content/uploads/2020/07/20200119_150343-2.jpg\" alt=\"Dellagrazia Extra Virgin Оливковое масло\" width=\"337\" height=\"253\" /> <img class=\"alignnone wp-image-847\" src=\"https://luculos.com/wp-content/uploads/2020/07/20200119_153320-2.jpg\" alt=\"Dellagrazia Extra Virgin Оливковое масло\" width=\"339\" height=\"254\" />\r\n<p class=\"western\">Dellagrazia Extra Virgin Olive Oil - продукт холодного отжима. Наши оливковые деревья выращиваются на солнечном острове Сирос. Живая роща расположена на юго-западе острова в прибрежном месте. Плод поглощает все полезные свойства морского воздуха.\r\nОливковое масло Dellagrazia Extra Virgin содержит характеристики, которые определяют качество оливкового масла, такие как богатый фруктовый аромат и освежающий вкус, а также мощный антиоксидантный эффект.\r\nОливковое масло Dellagrazia Extra Virgin имеет золотисто-зеленый оттенок, сбалансированный пряный вкус с продолжительным сладким легким послевкусием. Его замечательный фруктовый аромат с нотками груши и миндаля обусловлен сортом оливкового дерева \"Koroneiki\", из которого он производится.\r\nИнтегрированные методы выращивания и сбора урожая в сочетании с современными методами производства и хранения обеспечивают его особые характеристики и превосходное качество.</p>', 'Dellagrazia Extra Virgin Оливковое масло', '', 'publish', 'closed', 'closed', '', 'dellagrazia-extra-virgin-%d0%be%d0%bb%d0%b8%d0%b2%d0%ba%d0%be%d0%b2%d0%be%d0%b5-%d0%bc%d0%b0%d1%81%d0%bb%d0%be', '', '', '2020-07-17 18:55:18', '2020-07-17 18:55:18', '', 0, 'https://luculos.com/?post_type=al_product&#038;p=853', 0, 'al_product', '', 0),
(350, 1, '2018-04-24 12:16:45', '2018-04-24 12:16:45', 'Organic, dry, red wine from Mavroudi and Merlot varieties. The process from the harvest to the bottling ensures the excellent result of taste, flavor and aftertaste. His character unfolds at 16 -18 C and accompanies red meat and Meditettanean dishes.', 'Viston - BIO', 'Organic, dry, red wine from Mavroudi and Merlot varieties. The process from the harvest to the bottling ensures the excellent result of taste, flavor and aftertaste. His character unfolds at 16 -18 C and accompanies red meat and Meditettanean dishes.', 'publish', 'closed', 'closed', '', 'viston-bio-red-wine', '', '', '2018-05-15 17:37:54', '2018-05-15 17:37:54', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=350', 0, 'al_product', '', 0),
(351, 1, '2018-05-02 08:51:22', '2018-05-02 08:51:22', 'From organic grapes – sun-ripened\r\nA special sweet wine from local varieties with the ancient art of hanging grapes to the sun.\r\nIts honey-colored color reveals its maturity, while the nose is dominated by aromas of sweet caramel, raisins and nuts.\r\nNotes of dried figs and honey complete the aromatic profile and its seductive sweet taste.\r\nAt 12-14 ° C it is ideally combined with chocolate cakes or red pies.\r\n\r\n&nbsp;\r\n\r\nAus Bio-Trauben – Sonnengereift\r\nEin besonderer süßer Wein aus einheimischen Sorten mit der alten Kunst, Trauben an die Sonne zu hängen.\r\nSeine honigfarbene Farbe verrät seine Reife, während die Nase von Aromen von süßem Karamell, Rosinen und Nüssen dominiert wird.\r\nNoten von getrockneten Feigen und Honig ergänzen das aromatische Profil und seinen verführerisch süßen Geschmack.\r\nBei 12-14 °C wird er ideal mit Schokoladentorten oder roten Obstkuchen kombiniert.  375 ml', 'Melisandy - BIO', 'From organic grapes – sun-ripened\r\nA special sweet wine from local varieties with the ancient art of hanging grapes to the sun.\r\nIts honey-colored color reveals its maturity, while the nose is dominated by aromas of sweet caramel, raisins and nuts.\r\nNotes of dried figs and honey complete the aromatic profile and its seductive sweet taste.\r\nAt 12-14 ° C it is ideally combined with chocolate cakes or red pies.', 'publish', 'closed', 'closed', '', 'melisandy', '', '', '2018-05-15 16:56:27', '2018-05-15 16:56:27', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=351', 0, 'al_product', '', 0),
(353, 1, '2018-05-02 08:54:12', '2018-05-02 08:54:12', 'Organic red wine – dry\r\nIkaria: Protected Designation of Origin\r\nFrom our best vineyards we choose grapes of the varieties Fokianos and Mantilaria and after six months maturing in our barrels we offer you a special wine. Its color is ruby red and its nose is rich in red fruits and spices. Its lush character is complemented by the velvety taste and long aftertaste.\r\nEnjoy it at 16 – 18 ° C with cheese or red dishes of Mediterranean cuisine\r\n\r\n&nbsp;\r\n\r\nBiologischer Rotwein – Trocken\r\nIkaria: Geschützte Ursprungsbezeichnung\r\nAus unseren besten Weinbergen wählen wir Trauben der Sorten Fokianos und Mantilaria und nach sechs Monaten Reifung in unseren Fässern bieten wir Ihnen einen besonderen Wein an. Seine Farbe ist rubinrot und seine Nase ist reich an roten Früchten und Gewürzen. Sein üppiger Charakter wird durch den samtigen Geschmack und langen Nachgeschmack ergänzt.\r\nGenießen Sie  bei 16 – 18 °C mit Käse oder roten Gerichten der mediterranen Küche. 750 ml', 'Akratos - BIO', 'Organic red wine – dry\r\nIkaria: Protected Designation of Origin\r\nFrom our best vineyards we choose grapes of the varieties Fokianos and Mantilaria and after six months maturing in our barrels we offer you a special wine. Its color is ruby red and its nose is rich in red fruits and spices. Its lush character is complemented by the velvety taste and long aftertaste.\r\nEnjoy it at 16 – 18 ° C with cheese or red dishes of Mediterranean cuisine', 'publish', 'closed', 'closed', '', 'akratos', '', '', '2018-05-15 16:56:08', '2018-05-15 16:56:08', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=353', 0, 'al_product', '', 0),
(355, 1, '2018-05-02 08:56:02', '2018-05-02 08:56:02', 'Organic wine – semi dry rose\r\nIkaria: Protected Designation of Origin\r\nThe red varieties of our region and a cool way of making wine are the main ingredients of this cozy wine.\r\nIts color is pink, its nose is rich in wildflowers and red fruits and its taste is balanced with a sweet aftertaste.\r\nThe special character looks for dishes of Mediterranean cuisine and especially pasta or fish with red sauce.\r\nIt is drunk at 8-10 ° C.\r\n\r\n&nbsp;', 'Rosé - BIO', 'Organic wine – semi dry rose\r\nIkaria: Protected Designation of Origin\r\nThe red varieties of our region and a cool way of making wine are the main ingredients of this cozy wine.\r\nIts color is pink, its nose is rich in wildflowers and red fruits and its taste is balanced with a sweet aftertaste.\r\nThe special character looks for dishes of Mediterranean cuisine and especially pasta or fish with red sauce.\r\nIt is drunk at 8-10 ° C.', 'publish', 'closed', 'closed', '', 'rose-bio', '', '', '2018-05-15 16:55:27', '2018-05-15 16:55:27', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=355', 0, 'al_product', '', 0),
(356, 1, '2018-05-02 08:59:24', '2018-05-02 08:59:24', 'Organic white wine – dry\r\nIkaria: Protected Designation of Origin\r\nA special wine of the local variety Begleri.\r\nThe bright colors and aromas of fruits and wildflowers are the first elements that make up the image of the wine and make you taste it.\r\nIts balanced taste with a cool aftertaste complements the interplay of sensations and leaves the mouth with the best impressions.\r\nEnjoy at 8-10 ° C with fish or white meat dishes\r\n\r\n&nbsp;', 'Begleri - BIO', 'Organic white wine – dry\r\nIkaria: Protected Designation of Origin\r\nA special wine of the local variety Begleri.\r\nThe bright colors and aromas of fruits and wildflowers are the first elements that make up the image of the wine and make you taste it.\r\nIts balanced taste with a cool aftertaste complements the interplay of sensations and leaves the mouth with the best impressions.\r\nEnjoy at 8-10 ° C with fish or white meat dishes', 'publish', 'closed', 'closed', '', 'begleri', '', '', '2018-05-15 16:54:24', '2018-05-15 16:54:24', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=356', 0, 'al_product', '', 0),
(374, 1, '2018-05-11 16:54:56', '2018-05-11 16:54:56', 'Biologischer Weißwein – Trocken\r\n\r\nIkaria: Geschützte Ursprungsbezeichnung\r\n\r\nEin besonderer Wein der lokalen Sorte Begleri.\r\n\r\nDie hellen Farben und Aromen von Früchten und Wildblumen sind die ersten Elemente, die das Bild des Weins ausmachen und Sie dazu bringen, es zu kosten.\r\n\r\nSein ausgewogener Geschmack mit kühlem Nachgeschmack ergänzt das Zusammenspiel der Empfindungen und hinterlässt den Mund mit den besten Eindrücken.\r\n\r\nGenießen Sie bei 8-10 °C mit Fisch oder weiße Fleischgerichte. 750 ml', 'Begleri — BIO', 'Biologischer Weißwein – Trocken\r\n\r\nIkaria: Geschützte Ursprungsbezeichnung\r\n\r\nEin besonderer Wein der lokalen Sorte Begleri.\r\n\r\nDie hellen Farben und Aromen von Früchten und Wildblumen sind die ersten Elemente, die das Bild des Weins ausmachen und Sie dazu bringen, es zu kosten.\r\n\r\nSein ausgewogener Geschmack mit kühlem Nachgeschmack ergänzt das Zusammenspiel der Empfindungen und hinterlässt den Mund mit den besten Eindrücken.\r\n\r\nGenießen Sie bei 8-10 °C mit Fisch oder weiße Fleischgerichte. 750 ml', 'publish', 'closed', 'closed', '', 'begleri-bio-2', '', '', '2018-05-15 17:04:42', '2018-05-15 17:04:42', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=374', 0, 'al_product', '', 0),
(636, 1, '2018-10-03 11:17:55', '2018-10-03 11:17:55', '', 'Thaseon gi - Oregano', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-oregano', '', '', '2018-10-03 11:17:55', '2018-10-03 11:17:55', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=636', 0, 'al_product', '', 0),
(646, 1, '2018-10-03 11:18:35', '2018-10-03 11:18:35', '', 'Thaseon gi - Garlic', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-garlic', '', '', '2018-10-03 11:18:35', '2018-10-03 11:18:35', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=646', 0, 'al_product', '', 0),
(647, 1, '2018-10-03 11:19:10', '2018-10-03 11:19:10', '', 'Thaseon gi - Safran', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-safran', '', '', '2018-10-03 11:19:10', '2018-10-03 11:19:10', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=647', 0, 'al_product', '', 0),
(648, 1, '2018-10-03 11:19:56', '2018-10-03 11:19:56', '', 'Thaseon gi - Oregano', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-oregano-2', '', '', '2018-10-03 11:19:56', '2018-10-03 11:19:56', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=648', 0, 'al_product', '', 0),
(649, 1, '2018-10-03 11:20:36', '2018-10-03 11:20:36', '', 'Thaseon gi - Orange', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-orange', '', '', '2018-10-03 11:20:42', '2018-10-03 11:20:42', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=649', 0, 'al_product', '', 0),
(650, 1, '2018-10-03 11:22:11', '2018-10-03 11:22:11', '', 'Thaseon gi', '', 'publish', 'closed', 'closed', '', 'thaseon-gi', '', '', '2018-10-03 11:22:11', '2018-10-03 11:22:11', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=650', 0, 'al_product', '', 0),
(651, 1, '2018-10-03 11:22:37', '2018-10-03 11:22:37', '', 'Thaseon gi - Lemon', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-lemon', '', '', '2018-10-03 11:22:37', '2018-10-03 11:22:37', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=651', 0, 'al_product', '', 0),
(652, 1, '2018-10-03 11:23:58', '2018-10-03 11:23:58', '', 'Thaseon gi - Chilli pepper', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-chilli-pepper', '', '', '2018-10-03 11:23:58', '2018-10-03 11:23:58', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=652', 0, 'al_product', '', 0),
(653, 1, '2018-10-03 11:26:41', '2018-10-03 11:26:41', '', 'Thaseon gi - Rosemary', '', 'publish', 'closed', 'closed', '', 'thaseon-gi-rosemary', '', '', '2018-10-03 11:26:41', '2018-10-03 11:26:41', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=653', 0, 'al_product', '', 0),
(654, 1, '2018-10-03 13:46:54', '2018-10-03 13:46:54', '', 'Papayiannidi - Raspberry & Ouzo', '', 'publish', 'closed', 'closed', '', 'papayiannidi-raspberry-ouzo', '', '', '2018-10-03 13:46:54', '2018-10-03 13:46:54', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=654', 0, 'al_product', '', 0),
(676, 1, '2018-10-03 13:47:28', '2018-10-03 13:47:28', '', 'Papayiannidi - Peach & Ouzo', '', 'publish', 'closed', 'closed', '', 'papayiannidi-peach-ouzo', '', '', '2018-10-03 13:47:28', '2018-10-03 13:47:28', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=676', 0, 'al_product', '', 0),
(677, 1, '2018-10-03 13:48:30', '2018-10-03 13:48:30', '', 'Papayiannidi - Orange, tangerine & lemon', '', 'publish', 'closed', 'closed', '', 'papayiannidi-orange-tangerine-lemon', '', '', '2018-10-03 13:48:30', '2018-10-03 13:48:30', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=677', 0, 'al_product', '', 0),
(422, 1, '2018-05-02 08:56:02', '2018-05-02 08:56:02', 'Biologischer Wein – Semi trocken Rosé\r\n\r\nIkaria: Geschützte Ursprungsbezeichnung\r\nDie roten Sorten unserer Region und eine kühle Art der Weinherstellung sind die Hauptzutaten für diesen gemütlichen Wein.\r\nSeine Farbe ist rosa, seine Nase ist reich an Wildblumen und roten Früchten und sein Geschmack ist mit einem süßen Nachgeschmack ausgeglichen.\r\nDer besondere Charakter sucht nach Gerichten der mediterranen Küche und vor allem Pasta oder Fisch mit roter Sauce.\r\nEs wird bei 8-10 °C getrunken. 750 ml', 'Rosé - BIO', 'Biologischer Wein – Semi trocken Rosé\r\n\r\nIkaria: Geschützte Ursprungsbezeichnung\r\nDie roten Sorten unserer Region und eine kühle Art der Weinherstellung sind die Hauptzutaten für diesen gemütlichen Wein.\r\nSeine Farbe ist rosa, seine Nase ist reich an Wildblumen und roten Früchten und sein Geschmack ist mit einem süßen Nachgeschmack ausgeglichen.\r\nDer besondere Charakter sucht nach Gerichten der mediterranen Küche und vor allem Pasta oder Fisch mit roter Sauce.\r\nEs wird bei 8-10 °C getrunken. 750 ml', 'publish', 'closed', 'closed', '', 'rose-bio', '', '', '2018-05-15 17:18:37', '2018-05-15 17:18:37', '', 0, 'http://luculos.com/?product=rose-bio-2', 0, 'al_product', '', 0),
(678, 1, '2018-10-03 13:49:36', '2018-10-03 13:49:36', '', 'Papayiannidi - Tomato, spicy', '', 'publish', 'closed', 'closed', '', 'papayiannidi-tomato-spicy', '', '', '2018-10-03 13:49:36', '2018-10-03 13:49:36', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=678', 0, 'al_product', '', 0),
(423, 1, '2018-05-02 08:54:12', '2018-05-02 08:54:12', 'Biologischer Rotwein – Trocken\r\nIkaria: Geschützte Ursprungsbezeichnung\r\nAus unseren besten Weinbergen wählen wir Trauben der Sorten Fokianos und Mantilaria und nach sechs Monaten Reifung in unseren Fässern bieten wir Ihnen einen besonderen Wein an. Seine Farbe ist rubinrot und seine Nase ist reich an roten Früchten und Gewürzen. Sein üppiger Charakter wird durch den samtigen Geschmack und langen Nachgeschmack ergänzt.\r\nGenießen Sie  bei 16 – 18 °C mit Käse oder roten Gerichten der mediterranen Küche. 750 ml', 'Akratos - BIO', 'Biologischer Rotwein – Trocken\r\nIkaria: Geschützte Ursprungsbezeichnung\r\nAus unseren besten Weinbergen wählen wir Trauben der Sorten Fokianos und Mantilaria und nach sechs Monaten Reifung in unseren Fässern bieten wir Ihnen einen besonderen Wein an. Seine Farbe ist rubinrot und seine Nase ist reich an roten Früchten und Gewürzen. Sein üppiger Charakter wird durch den samtigen Geschmack und langen Nachgeschmack ergänzt.\r\nGenießen Sie  bei 16 – 18 °C mit Käse oder roten Gerichten der mediterranen Küche. 750 ml', 'publish', 'closed', 'closed', '', 'akratos', '', '', '2018-05-15 17:15:08', '2018-05-15 17:15:08', '', 0, 'http://luculos.com/?product=akratos-2', 0, 'al_product', '', 0),
(679, 1, '2018-10-03 13:50:22', '2018-10-03 13:50:22', '', 'Papayiannidi - Tomato & basil', '', 'publish', 'closed', 'closed', '', 'papayiannidi-tomato-basil', '', '', '2018-10-03 13:50:22', '2018-10-03 13:50:22', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=679', 0, 'al_product', '', 0),
(424, 1, '2018-05-02 08:51:22', '2018-05-02 08:51:22', 'Aus Bio-Trauben – Sonnengereift\r\nEin besonderer süßer Wein aus einheimischen Sorten mit der alten Kunst, Trauben an die Sonne zu hängen.\r\nSeine honigfarbene Farbe verrät seine Reife, während die Nase von Aromen von süßem Karamell, Rosinen und Nüssen dominiert wird.\r\nNoten von getrockneten Feigen und Honig ergänzen das aromatische Profil und seinen verführerisch süßen Geschmack.\r\nBei 12-14 °C wird er ideal mit Schokoladentorten oder roten Obstkuchen kombiniert.  375 ml', 'Melisandy - BIO', 'Aus Bio-Trauben – Sonnengereift\r\nEin besonderer süßer Wein aus einheimischen Sorten mit der alten Kunst, Trauben an die Sonne zu hängen.\r\nSeine honigfarbene Farbe verrät seine Reife, während die Nase von Aromen von süßem Karamell, Rosinen und Nüssen dominiert wird.\r\nNoten von getrockneten Feigen und Honig ergänzen das aromatische Profil und seinen verführerisch süßen Geschmack.\r\nBei 12-14 °C wird er ideal mit Schokoladentorten oder roten Obstkuchen kombiniert.  375 ml', 'publish', 'closed', 'closed', '', 'melisandy', '', '', '2018-05-15 17:11:34', '2018-05-15 17:11:34', '', 0, 'http://luculos.com/?product=melisandy-2', 0, 'al_product', '', 0),
(680, 1, '2018-10-03 13:51:32', '2018-10-03 13:51:32', '', 'Papayiannidi - Tomato, balsamic vinegard & peppers', '', 'publish', 'closed', 'closed', '', 'papayiannidi-tomato-balsamic-vinegard-peppers', '', '', '2018-10-03 13:51:32', '2018-10-03 13:51:32', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=680', 0, 'al_product', '', 0),
(425, 1, '2018-04-24 12:16:45', '2018-04-24 12:16:45', 'Organic, dry, red wine from Mavroudi and Merlot varieties. The process from the harvest to the bottling ensures the excellent result of taste, flavor and aftertaste. His character unfolds at 16 -18 C and accompanies red meat and Meditettanean dishes.', 'Viston - BIO', 'Organic, dry, red wine from Mavroudi and Merlot varieties. The process from the harvest to the bottling ensures the excellent result of taste, flavor and aftertaste. His character unfolds at 16 -18 C and accompanies red meat and Meditettanean dishes.', 'publish', 'closed', 'closed', '', 'viston-bio-red-wine', '', '', '2018-05-15 17:37:54', '2018-05-15 17:37:54', '', 0, 'http://luculos.com/?product=viston-bio-red-wine-2', 0, 'al_product', '', 0),
(681, 1, '2018-10-03 13:52:07', '2018-10-03 13:52:07', '', 'Papayiannidi - Tomato & orange', '', 'publish', 'closed', 'closed', '', 'papayiannidi-tomato-orange', '', '', '2018-10-03 13:52:07', '2018-10-03 13:52:07', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=681', 0, 'al_product', '', 0),
(426, 1, '2018-03-19 15:35:26', '2018-03-19 15:35:26', 'Dieser Wein ist eine meisterhafte Mischung aus der griechischen Sorte Mavroudi von Thrakien mit fünfundachtzig Prozent und von Merlot mit fünfzehn Prozent. Die Trauben sind perfekt und gesund gereift. Ihre Ernte am frühen Morgen und ihre Beförderung zum Weingut innerhalb einer Stunde  macht die Weinbereitung direkt nach der Traubenaufnahme möglich. Bei der Anwendung der klassischen roten Weinbereitung mit langer Extraktion werden folgenden Stufen verfolgt: Trauben ernten, entstielen und zerkleinern, ohne gepresst zu werden. Das  führt zu einem außergewöhnlichen Qualitätswein. Die Temperatur der alkoholischen Gärung wird streng auf 26 C in automatischen Vinifikatoren von fünf Tonnen gehalten und die Fermentation findet in Eichenfässer statt.', 'Apocalypsis -BIO', 'Dieser Wein ist eine meisterhafte Mischung aus der griechischen Sorte Mavroudi von Thrakien mit fünfundachtzig Prozent und von Merlot mit fünfzehn Prozent. Die Trauben sind perfekt und gesund gereift. Ihre Ernte am frühen Morgen und ihre Beförderung zum Weingut innerhalb einer Stunde  macht die Weinbereitung direkt nach der Traubenaufnahme möglich. Bei der Anwendung der klassischen roten Weinbereitung mit langer Extraktion werden folgenden Stufen verfolgt: Trauben ernten, entstielen und zerkleinern, ohne gepresst zu werden. Das  führt zu einem außergewöhnlichen Qualitätswein. Die Temperatur der alkoholischen Gärung wird streng auf 26 C in automatischen Vinifikatoren von fünf Tonnen gehalten und die Fermentation findet in Eichenfässer statt.', 'publish', 'closed', 'closed', '', 'apocalypsis', '', '', '2018-05-15 17:23:25', '2018-05-15 17:23:25', '', 0, 'http://luculos.com/?product=apocalypsis-2', 0, 'al_product', '', 0),
(682, 1, '2018-10-03 13:52:46', '2018-10-03 13:52:46', '', 'Papayiannidi - Tomato & Aubergine', '', 'publish', 'closed', 'closed', '', 'papayiannidi-tomato-aubergine', '', '', '2018-10-03 13:52:46', '2018-10-03 13:52:46', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=682', 0, 'al_product', '', 0),
(683, 1, '2018-10-03 13:53:24', '2018-10-03 13:53:24', '', 'Papayiannidi - Tomato, olives & ouzo', '', 'publish', 'closed', 'closed', '', 'papayiannidi-tomato-olives-ouzo', '', '', '2018-10-03 13:53:24', '2018-10-03 13:53:24', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=683', 0, 'al_product', '', 0),
(684, 1, '2018-10-03 13:54:26', '2018-10-03 13:54:26', '', 'Papayiannidi - Forest fruits & honey', '', 'publish', 'closed', 'closed', '', 'papayiannidi-forest-fruits-honey', '', '', '2018-10-03 13:54:26', '2018-10-03 13:54:26', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=684', 0, 'al_product', '', 0),
(685, 1, '2018-10-03 13:55:10', '2018-10-03 13:55:10', '', 'Papayiannidi - Strawberry & chocolate', '', 'publish', 'closed', 'closed', '', 'papayiannidi-strawberry-chocolate', '', '', '2018-10-03 13:55:10', '2018-10-03 13:55:10', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=685', 0, 'al_product', '', 0),
(686, 1, '2018-10-03 13:56:08', '2018-10-03 13:56:08', '', 'Thrakiotiki zimi - chilopitaki', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-chilopitaki', '', '', '2018-10-03 13:56:08', '2018-10-03 13:56:08', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=686', 0, 'al_product', '', 0),
(687, 1, '2018-10-03 13:56:36', '2018-10-03 13:56:36', '', 'Thrakiotiki zimi - Vides', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-vides', '', '', '2018-10-03 13:56:36', '2018-10-03 13:56:36', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=687', 0, 'al_product', '', 0),
(688, 1, '2018-10-03 13:57:40', '2018-10-03 13:57:40', '', 'Thrakiotiki zimi - Sterile Trachana', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-sterile-trachana', '', '', '2018-10-03 13:57:40', '2018-10-03 13:57:40', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=688', 0, 'al_product', '', 0),
(689, 1, '2018-10-03 13:58:58', '2018-10-03 13:58:58', '', 'Thrakiotiki zimi - Trachana with yogurt (Sweet)', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-trachana-with-yogurt-sweet', '', '', '2018-10-03 13:58:58', '2018-10-03 13:58:58', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=689', 0, 'al_product', '', 0),
(690, 1, '2018-10-03 13:59:46', '2018-10-03 13:59:46', '', 'Thrakiotiki zimi - Trachana with vegetables (Sweet)', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-trachana-with-vegetables-sweet', '', '', '2018-10-03 13:59:46', '2018-10-03 13:59:46', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=690', 0, 'al_product', '', 0),
(691, 1, '2018-10-03 14:00:24', '2018-10-03 14:00:24', '', 'Thrakiotiki zimi - Trachana with milk (Sweet)', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-trachana-with-milk-sweet', '', '', '2018-10-03 14:00:24', '2018-10-03 14:00:24', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=691', 0, 'al_product', '', 0),
(692, 1, '2018-10-03 14:00:55', '2018-10-03 14:00:55', '', 'Thrakiotiki zimi - Pligouri', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-pligouri', '', '', '2018-10-03 14:00:55', '2018-10-03 14:00:55', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=692', 0, 'al_product', '', 0),
(693, 1, '2018-10-03 14:01:19', '2018-10-03 14:01:19', '', 'Thrakiotiki zimi - Orzo', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-orzo', '', '', '2018-10-03 14:01:19', '2018-10-03 14:01:19', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=693', 0, 'al_product', '', 0),
(694, 1, '2018-10-03 14:02:14', '2018-10-03 14:02:14', '', 'Thrakiotiki zimi - Mac', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-mac', '', '', '2018-10-03 14:02:14', '2018-10-03 14:02:14', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=694', 0, 'al_product', '', 0),
(695, 1, '2018-10-03 14:03:23', '2018-10-03 14:03:23', '', 'Thrakiotiki zimi - Unsold wheat', '', 'publish', 'closed', 'closed', '', 'thrakiotiki-zimi-unsold-wheat', '', '', '2018-10-03 14:03:23', '2018-10-03 14:03:23', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=695', 0, 'al_product', '', 0),
(206, 1, '2018-03-19 15:35:26', '2018-03-19 15:35:26', '<div class=\"woocommerce-product-details__short-description\">\r\n\r\nThis wine is a masterly blend of the Greek variety Mavroudi of Thrace at eighty-five percent and Merlot at fifteen percent. The grapes have matured perfectly and healthy. Their early morning harvest and their promotion to the winery within one hour makes wine making possible right after grape picking. In the application of the classic red winemaking with long extraction, the following stages are followed: Harvesting grapes, stalking and mincing, without being pressed. This leads to an exceptional quality wine. The temperature of the alcoholic fermentation is kept strictly at 26 C in automatic vatifiers of five tons and the fermentation takes place in oak barrels\r\n\r\n</div>', 'Apocalypsis -BIO', '<div class=\"woocommerce-product-details__short-description\">\r\n\r\nThis wine is a masterly blend of the Greek variety Mavroudi of Thrace at eighty-five percent and Merlot at fifteen percent. The grapes have matured perfectly and healthy. Their early morning harvest and their promotion to the winery within one hour makes wine making possible right after grape picking. In the application of the classic red winemaking with long extraction, the following stages are followed: Harvesting grapes, stalking and mincing, without being pressed. This leads to an exceptional quality wine. The temperature of the alcoholic fermentation is kept strictly at 26 C in automatic vatifiers of five tons and the fermentation takes place in oak barrels\r\n\r\n</div>', 'publish', 'closed', 'closed', '', 'apocalypsis', '', '', '2018-05-15 17:08:46', '2018-05-15 17:08:46', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=206', 0, 'al_product', '', 0),
(731, 1, '2018-10-04 22:33:51', '2018-10-04 22:33:51', 'Παράγεται από 100% φρέσκο Ελληνικό αγελαδινό γάλα όπου συλλέγεται από επιλεγμένους γαλακτοπαραγωγούς της περιοχής της Θράκης. Μεστή και πλούσια γεύση καθώς όλα τα συστατικά του γάλακτος παραμένουν αναλλοίωτα στο τυρί διότι δεν αφαιρείται η κρέμα από το γάλα. Με όποιον τρόπο και αν επιλέξετε να το απολαύσετε (σκέτο, σαγανάκι ,με λαδορίγανη, σε σαλάτες, πίτες κλπ) το γευστικό αποτέλεσμα θα σας ικανοποιήσει απόλυτα, καθώς και η προσιτή τιμή του!', 'Cow Cheese', '', 'pending', 'closed', 'closed', '', 'cowcheese', '', '', '2020-07-17 19:19:37', '2020-07-17 19:19:37', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=731', 0, 'al_product', '', 0),
(737, 1, '2018-10-04 22:37:43', '2018-10-04 22:37:43', 'Παράγεται από 100 % φρέσκο Ελληνικό κατσικίσιο γάλα όπου συλλέγεται από τον ορεινό όγκο της Θράκης από ντόπια κοπάδια χαμηλής γαλακτοπαραγωγής, όπου βόσκουν μέσα στην παρθένα φύση της Ροδόπης με αποτέλεσμα το γάλα να είναι πλούσιο σε ποιοτικά χαρακτηριστικά αποδίδοντας στο τυρί δυνατή γεύση.', 'Goat Cheese', '', 'pending', 'closed', 'closed', '', 'goatcheese', '', '', '2020-07-17 19:19:28', '2020-07-17 19:19:28', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=737', 0, 'al_product', '', 0),
(748, 1, '2018-10-04 22:42:07', '2018-10-04 22:42:07', 'Παράγεται από 100 % φρέσκο Ελληνικό πρόβειο και κατσικίσιο γάλα της περιοχής της Θράκης. Παραδοσιακή συνταγή που ικανοποιεί και τους πιο απαιτητικούς μιας και το αιγοπρόβειο γάλα προσδίδει γευστική ένταση στο τυρί. Μεστή και πλούσια γεύση καθώς όλα τα συστατικά του γάλακτος παραμένουν αναλλοίωτα στο τυρί.', 'Sheep & Goat Cheese', '', 'pending', 'closed', 'closed', '', 'sheepgoat', '', '', '2020-07-17 19:19:20', '2020-07-17 19:19:20', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=748', 0, 'al_product', '', 0),
(754, 1, '2018-10-04 22:44:23', '2018-10-04 22:44:23', 'Παράγεται από 100 % φρέσκο Ελληνικό αγελαδινό και αιγοπρόβειο γάλα όπου συλλέγεται την περιοχή της Θράκης. Πρωτότυπη συνταγή με ιδιαίτερες γεύσης λόγο της προσθήκης πρόβειου και κατσικίσιου γάλακτος που ικανοποιεί μεγάλο εύρος καταναλωτικού κοινού λόγω της ήπιας αλλά ευχάριστης γεύσης του αλλά και της προσιτής τιμής του.', 'Mixed cheese', '', 'publish', 'closed', 'closed', '', 'mixcheese', '', '', '2019-04-24 12:13:03', '2019-04-24 12:13:03', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=754', 0, 'al_product', '', 0),
(756, 1, '2018-10-04 22:45:45', '2018-10-04 22:45:45', 'Παράγεται από 100 % ολόφρεσκο Ελληνικό γάλα ημέρας, ένα γάλα γλυκό και πυκνό, όπου συλλέγεται από επιλεγμένους γαλακτοπαραγωγούς την περιοχής της Θράκης διατηρώντας όλα τα θρεπτικά συστατικά. Προϊόν ανώτερης ποιότητας, ιδιαίτερη γεύση και κρεμώδης υφή, ιδανικό να ικανοποιήσει γευστικά κάθε ηλικίας καταναλωτικό κοινό .', 'Cow yogurt', '', 'pending', 'closed', 'closed', '', 'cowyogurt', '', '', '2020-07-17 19:19:12', '2020-07-17 19:19:12', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=756', 0, 'al_product', '', 0),
(501, 1, '2018-03-19 15:35:26', '2018-03-19 15:35:26', 'АПОКАЛИПСИС\r\n\r\nЭто вино – виртуозная смесь греческого фракийского сорта Мавроуди и сорта Мерло.Из винограда высокого качества,хорошо созревшего. Урожай собирается рано утром и перевозка в винодельню происходит ровно через час после сбора.\r\n\r\nПрименение классической красной винификации с длительной экстракцией происходит по следующим шагам: сбор урожая винограда, дестабилизация и дробление без давления. Таким образом мы достигаем превосходного качества вина, которое вы видите, и вы можете им насладиться. Температура алкогольной ферментации строго контролируется на уровне 26 градусов и производится в автоматических виноделах по 5 тонн и происходит ферментация в дубовых бочках.', 'Apocalypsis -BIO', 'АПОКАЛИПСИС\r\n\r\nЭто вино – виртуозная смесь греческого фракийского сорта Мавроуди и сорта Мерло.Из винограда высокого качества,хорошо созревшего. Урожай собирается рано утром и перевозка в винодельню происходит ровно через час после сбора.\r\n\r\nПрименение классической красной винификации с длительной экстракцией происходит по следующим шагам: сбор урожая винограда, дестабилизация и дробление без давления. Таким образом мы достигаем превосходного качества вина, которое вы видите, и вы можете им насладиться. Температура алкогольной ферментации строго контролируется на уровне 26 градусов и производится в автоматических виноделах по 5 тонн и происходит ферментация в дубовых бочках.', 'publish', 'closed', 'closed', '', 'apocalypsis', '', '', '2018-05-15 17:36:52', '2018-05-15 17:36:52', '', 0, 'http://luculos.com/?product=apocalypsis-2', 0, 'al_product', '', 0),
(503, 1, '2018-05-02 08:51:22', '2018-05-02 08:51:22', 'Melisandy МЕЛИСАНДИ\r\n\r\nЗащитная географическая зона.\r\n\r\nКрасное вяленное биологическое вино Икарии.\r\n\r\nВремя созревания в бочках 24 месяца.\r\n\r\n375 мл - 15,5% .\r\n\r\nУникальное сладкое вино из местных сортов с\r\n\r\nособым искусством высушивания винограда на солнце.\r\n\r\nЗрелость вина определяется по янтарному цвету.Доминируют ароматы карамели,изюма и сушенных орешков.Утонченность вина дополняется привкусом черного шоколада.\r\n\r\nПри 12-14˚C вино идеально сочетается со сладкими блюдами и десертом.', 'Melisandy - BIO', 'Melisandy МЕЛИСАНДИ\r\n\r\nЗащитная географическая зона.\r\n\r\nКрасное вяленное биологическое вино Икарии.\r\n\r\nВремя созревания в бочках 24 месяца.\r\n\r\n375 мл - 15,5% .\r\n\r\nУникальное сладкое вино из местных сортов с\r\n\r\nособым искусством высушивания винограда на солнце.\r\n\r\nЗрелость вина определяется по янтарному цвету.Доминируют ароматы карамели,изюма и сушенных орешков.Утонченность вина дополняется привкусом черного шоколада.\r\n\r\nПри 12-14˚C вино идеально сочетается со сладкими блюдами и десертом.', 'publish', 'closed', 'closed', '', 'melisandy', '', '', '2018-05-15 17:13:04', '2018-05-15 17:13:04', '', 0, 'http://luculos.com/?product=melisandy-2', 0, 'al_product', '', 0),
(504, 1, '2018-05-02 08:54:12', '2018-05-02 08:54:12', 'Akratos  - АКРАТОС\r\n\r\nЗащитная географическая зона.\r\n\r\nКрасное сухое биологическое вино Икарии.\r\n\r\n750 мл - 14.%.\r\n\r\nИз лучших виноградников выбираем разновидности Фокианоса и Мандилиарии. Шесть месяцев виноград созревает в бочках для получения этого вида вина ,бордового цвета с привкусом красных фруктов и специй.\r\n\r\nНаслаждайтесь вином,охлажденным при тепературе 16 - 18 ° C .\r\n\r\nПодается к мясным блюдам и к закускам из сыров.', 'Akratos - BIO', 'Άκρατος АКРАТОС\r\n\r\nЗащитная географическая зона.\r\n\r\nКрасное сухое биологическое вино Икарии.\r\n\r\n750 мл - 14.%.\r\n\r\nИз лучших виноградников выбираем разновидности Фокианоса и Мандилиарии. Шесть месяцев виноград созревает в бочках для получения этого вида вина ,бордового цвета с привкусом красных фруктов и специй.\r\n\r\nНаслаждайтесь вином,охлажденным при тепературе 16 - 18 ° C .\r\n\r\nПодается к мясным блюдам и к закускам из сыров.', 'publish', 'closed', 'closed', '', 'akratos', '', '', '2018-05-15 17:16:39', '2018-05-15 17:16:39', '', 0, 'http://luculos.com/?product=akratos-2', 0, 'al_product', '', 0),
(506, 1, '2018-05-02 08:56:02', '2018-05-02 08:56:02', 'РОЗОВОЕ ВИНО\r\n\r\nЗащитная географическая зона.\r\n\r\nРозовое,полусухое биологическое вино Икарии.\r\n\r\n750 мл - 13%\r\n\r\nКрасные сорта винограда нашего региона и прохладный метод виноделия являются важными по существу критериями для создания этого замечательного вина розового цвета,совмещающее запах диких цветов и красных фруктов,создавая сладкий привкус.\r\n\r\nОсобый характер этого вина идеально сочетается с блюдами из макаронных изделий и также подается к рыбным блюдам.\r\n\r\nНаслаждайтесь этим вином,охлаженным до 8-10 ° C.', 'Rosé - BIO', 'РОЗОВОЕ ВИНО\r\n\r\nЗащитная географическая зона.\r\n\r\nРозовое,полусухое биологическое вино Икарии.\r\n\r\n750 мл - 13%\r\n\r\nКрасные сорта винограда нашего региона и прохладный метод виноделия являются важными по существу критериями для создания этого замечательного вина розового цвета,совмещающее запах диких цветов и красных фруктов,создавая сладкий привкус.\r\n\r\nОсобый характер этого вина идеально сочетается с блюдами из макаронных изделий и также подается к рыбным блюдам.\r\n\r\nНаслаждайтесь этим вином,охлаженным до 8-10 ° C.', 'publish', 'closed', 'closed', '', 'rose-bio', '', '', '2018-05-15 17:20:07', '2018-05-15 17:20:07', '', 0, 'http://luculos.com/?product=rose-bio-2', 0, 'al_product', '', 0),
(507, 1, '2018-05-11 16:54:56', '2018-05-11 16:54:56', 'БЕГЛЕРИ\r\n\r\nЗащитная географическая область.\r\n\r\nБелое сухое биологическое вино Икарии.\r\n\r\n750 мл - 12,5 градусов.\r\n\r\nС местного сорта Beglijri,винограда,выращенного\r\n\r\nв объятиях моря, светлого цвета с ароматом цитрусовых(цветов лимона и грейпфрута).\r\n\r\nБаланс вкусов оставляет во рту приятное ощущение ананаса и персика.\r\n\r\nИдеально подходит к блюдам Средиземной кухни.\r\n\r\nНаслаждайтесь им ,охлажденным до 8-10 ° C.', 'Begleri — BIO', 'БЕГЛЕРИ\r\n\r\nЗащитная географическая область.\r\n\r\nБелое сухое биологическое вино Икарии.\r\n\r\n750 мл - 12,5 градусов.\r\n\r\nС местного сорта Beglijri,винограда,выращенного\r\n\r\nв объятиях моря, светлого цвета с ароматом цитрусовых(цветов лимона и грейпфрута).\r\n\r\nБаланс вкусов оставляет во рту приятное ощущение ананаса и персика.\r\n\r\nИдеально подходит к блюдам Средиземной кухни.\r\n\r\nНаслаждайтесь им ,охлажденным до 8-10 ° C.', 'publish', 'closed', 'closed', '', 'begleri-bio-2', '', '', '2018-05-15 17:21:51', '2018-05-15 17:21:51', '', 0, 'http://luculos.com/?product=begleri-bio-2-2', 0, 'al_product', '', 0),
(509, 1, '2018-05-15 17:27:19', '2018-05-15 17:27:19', 'Organic red wine – dry\r\nIkaria: Protected Designation of Origin\r\nThe lively variety Fokiano and the luscious Kountouro (Mandilaria) combine their virtues in a ruby red wine, with aromas of wildflowers and black fruits, with a full flavor and a long aftertaste.\r\nIts special character, at 15 – 17 ° C, seeks fried meat and red dishes of Mediterranean cuisine', 'Lagyros -BIO', 'Organic red wine – dry\r\nIkaria: Protected Designation of Origin\r\nThe lively variety Fokiano and the luscious Kountouro (Mandilaria) combine their virtues in a ruby red wine, with aromas of wildflowers and black fruits, with a full flavor and a long aftertaste.\r\nIts special character, at 15 – 17 ° C, seeks fried meat and red dishes of Mediterranean cuisine', 'publish', 'closed', 'closed', '', 'lagyros', '', '', '2018-05-15 17:27:56', '2018-05-15 17:27:56', '', 0, 'http://luculos.com/?post_type=al_product&#038;p=509', 0, 'al_product', '', 0),
(511, 1, '2018-05-15 17:27:19', '2018-05-15 17:27:19', 'Biologischer Rotwein – Trocken\r\n\r\nIkaria: Geschützte Ursprungsbezeichnung\r\n\r\nDie lebhafte Rebsorte Fokiano und die üppige Kountouro (Mandilaria) vereinen ihre Tugenden in einem rubinroten Wein, mit Aromen von Wildblumen und schwarzen Früchten, mit einem vollem  Geschmack und einem langen Nachgeschmack.\r\n\r\nSein besonderer Charakter, bei 15 – 17 °C, sucht gebratenes Fleisch und rote Gerichte der mediterranen Küche. 750 ml', 'Lagyros -BIO', 'Biologischer Rotwein – Trocken\r\n\r\nIkaria: Geschützte Ursprungsbezeichnung\r\n\r\nDie lebhafte Rebsorte Fokiano und die üppige Kountouro (Mandilaria) vereinen ihre Tugenden in einem rubinroten Wein, mit Aromen von Wildblumen und schwarzen Früchten, mit einem vollem  Geschmack und einem langen Nachgeschmack.\r\n\r\nSein besonderer Charakter, bei 15 – 17 °C, sucht gebratenes Fleisch und rote Gerichte der mediterranen Küche. 750 ml', 'publish', 'closed', 'closed', '', 'lagyros', '', '', '2018-05-15 17:28:38', '2018-05-15 17:28:38', '', 0, 'http://luculos.com/?product=lagyros-2', 0, 'al_product', '', 0);

--
-- Ευρετήρια για άχρηστους πίνακες
--

--
-- Ευρετήρια για πίνακα `8RyLi_posts`
--
ALTER TABLE `8RyLi_posts`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `post_name` (`post_name`(191)),
  ADD KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
  ADD KEY `post_parent` (`post_parent`),
  ADD KEY `post_author` (`post_author`);

--
-- AUTO_INCREMENT για άχρηστους πίνακες
--

--
-- AUTO_INCREMENT για πίνακα `8RyLi_posts`
--
ALTER TABLE `8RyLi_posts`
  MODIFY `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=915;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
